### ISSUE TITLE
Incorrect Japanese Kanji Display on Android with Japanese Locale

### ISSUE THREAD

**Issue by edo-bari-ikutsu** [s3drive/app#65]
When an Android device is set to the Japanese language, some Kanji characters in the S3Drive app are displayed in their Chinese form instead of their Japanese form.

![Image](https://github.com/user-attachments/assets/058ce50c-a07e-4bd1-9cfe-6ed0d0234e17)

I understand S3Drive uses Flutter. I propose that the app should detect the device's language setting upon startup and adjust the font rendering accordingly.

```Dart
class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Retrieve locale of the terminal without countryCode
    // to avoid misconfiguration of font in some OPPO terminal
    var locale = WidgetsBinding.instance.platformDispatcher.locale;
    locale = Locale.fromSubtags(
      languageCode: locale.languageCode,
      scriptCode: locale.scriptCode,
    );
    return MaterialApp(
      // set locale of the terminal to supportedLocales
      supportedLocales: [locale],
      home: ...
    );
  }
}
```

I've tested a solution where the Japanese Kanji displayed correctly on Android terminals set to Japanese. 

![Image](https://github.com/user-attachments/assets/19dc6f59-67e9-4651-b125-ad1079c4b8aa)

Conversely, on Android terminals with non-Japanese language settings, Chinese Kanji were displayed, which is the expected behavior.

![Image](https://github.com/user-attachments/assets/baf67636-9661-4596-9a4c-d44cda0b62af)

Full sample code content is available as follows:
https://github.com/edo-bari-ikutsu/flutter-font-eval

**Comment by tomekit** [comment]
Thank you for your feedback and detailed explanations. 

We'll try to squeeze this in a next release!

**Comment by edo-bari-ikutsu** [comment]
With the recent release of S3Drive (v1.14.3), Japanese Kanji is now displayed correctly. Thank you for implementing this fix!

<img width="1080" height="443" alt="Image" src="https://github.com/user-attachments/assets/b5da45fb-9817-4893-a374-9d4131a685e6" />

**Comment by edo-bari-ikutsu** [comment]
Following the update to version 1.14.4 (build: 10140400), the display of Japanese kanji has once again become incorrect. 

<img width="720" height="263" alt="Image" src="https://github.com/user-attachments/assets/7cc6e257-ae9a-494f-9549-2c0aa7e402ed" />

I suspect this is a side effect of the recent localization fixes (#67 and #69).

**Comment by tomekit** [comment]
Hi @edo-bari-ikutsu and sorry for the delay,

I've found some time to test this again and either I am misunderstanding Kanji/Hans gotchas or with some newer Flutter releases this problem was resolved automatically.

As of now, when I've tried to test `Today` it appears seemingly correct with Japanese Kanji.

<img width="176" height="215" alt="Image" src="https://github.com/user-attachments/assets/df46a1f2-87fa-48f2-ad18-0202c65726d8" />

<img width="285" height="132" alt="Image" src="https://github.com/user-attachments/assets/7fb3ca99-ba5a-497a-afde-eda4ea563fd1" />

Can you try it on your end using latest release and let me know?

Thanks

**Comment by edo-bari-ikutsu** [comment]
Thank you for your attention to this matter. Unfortunately, the kanji font issue persists on my smartphone (details below).

<img width="718" height="148" alt="Image" src="https://github.com/user-attachments/assets/64d5b50b-e32f-4835-b685-cd1dd88ac317" />

My smartphone environment:
+ Motorola moto g53y 5G (Android 14)
+ S3Drive v1.15.7 (build: 10150702)
